% Step2_Calculate_Nodal_Reorganization
%
% Purpose:
% Calculate patient-level nodal connectivity reconfiguration and nodal
% morphometric reorganization percentage from standardized regional
% features. TJU and JLH patients follow one shared calculation path. TJU
% patient values are additionally standardized against longitudinal healthy
% control change, whereas JLH values remain descriptive raw measures.
%
% This script performs subject level measurement and normative
% standardization only. Group level effect estimates, hypothesis tests,
% contrast definitions, multiple testing families, and FDR correction are
% implemented in Step3_Run_Nodal_Reorganization_Statistics.m.
% One compact numeric Block 2 input is retained per patient in both the
% Original and Laterality Normalized representations.
%
% Author: Qirui Zhang
% Created: 31 August 2026

%% Section 1 Set project configuration
% Define the cohorts, analysis representations, session direction, atlas
% orientations, fixed surgical overlap threshold, and project relative paths.

clear;
clc;

this_file = mfilename('fullpath');
project_root = fileparts(fileparts(fileparts(fileparts(this_file))));
addpath(fullfile(project_root, 'src', 'utils'));

dataset_names = ["TJU", "JLH"]; % Center order.
analysis_modes = ["Original", "Laterality_Normalized"]; % Anatomical and normalized modes.

orientation_labels = ["Original", "Flipped_LR"]; % Original and flipped atlas order.
surgery_overlap_threshold_percent = 5; % ROI exclusion threshold in percent.

metadata_root = fullfile(project_root, 'Data', 'metadata');
feature_root = fullfile(project_root, 'Data');
result_root = fullfile( ...
    project_root, 'results', 'Block1_TLE_surgery_reorganization');
atlas_lut_file = fullfile( ...
    project_root, 'Data', 'atlas', 'cocoyeo143_LUT.txt');
original_surgery_atlas_file = fullfile( ...
    project_root, 'Data', 'atlas', ...
    'cocoyeo143_dil2_allsubj_mode.nii.gz');
surgery_atlas_sources = [ ...
    string(fullfile('Data', 'atlas', ...
    'cocoyeo143_dil2_allsubj_mode.nii.gz')); ...
    string(fullfile('Data', 'atlas', ...
    'cocoyeo143_dil2_allsubj_mode_flipLR.nii.gz'))];
bold_atlas_sources = [ ...
    string(fullfile('Data', 'atlas', ...
    'cocoyeo143_XCPD_BOLD_grid_2mm.nii.gz')); ...
    string(fullfile('Data', 'atlas', ...
    'cocoyeo143_XCPD_BOLD_grid_2mm_flipLR.nii.gz'))];

%% Section 2 Load ROI definitions and hemisphere interpretations
% Retain the 116 noncerebellar ROIs and assign anatomical and normalized
% hemisphere labels used in the two analysis representations.

atlas_table = read_cocoyeo143_lut(string(atlas_lut_file));
atlas_table = atlas_table( ...
    ~startsWith(atlas_table.ROI_Name, "Cbm"), :);
roi_ids = atlas_table.ROI_ID; % 116 x 1 ROI IDs in atlas order.
roi_names = atlas_table.ROI_Name; % 116 x 1 ROI names in atlas order.
roi_networks = atlas_table.Network; % 116 x 1 network labels in atlas order.
n_rois = height(atlas_table); % Number of retained noncerebellar ROIs.

anatomical_hemisphere = strings(n_rois, 1);
left_roi_mask = startsWith(roi_names, "Left-") ...
    | startsWith(roi_names, "lh.");
right_roi_mask = startsWith(roi_names, "Right-") ...
    | startsWith(roi_names, "rh.");
anatomical_hemisphere(left_roi_mask) = "Anatomical_Left";
anatomical_hemisphere(right_roi_mask) = "Anatomical_Right";
normalized_hemisphere = strings(n_rois, 1);
normalized_hemisphere(left_roi_mask) = "Ipsilateral"; % Operated side after normalization.
normalized_hemisphere(right_roi_mask) = "Contralateral"; % Opposite side after normalization.

%% Section 3 Create result directories
% Create the approved subject level and compact Block 2 handoff directories
% for each dataset and analysis representation.

result_dirs = cell(2, 2);
block2_input_dirs = cell(2, 2);

for dataset_index = 1:2
    for mode_index = 1:2
        result_dirs{dataset_index, mode_index} = fullfile( ...
            result_root, dataset_names(dataset_index), ...
            analysis_modes(mode_index));
        block2_input_dirs{dataset_index, mode_index} = fullfile( ...
            result_dirs{dataset_index, mode_index}, 'block2_inputs');

        mkdir(result_dirs{dataset_index, mode_index});
        mkdir(block2_input_dirs{dataset_index, mode_index});
    end
end

%% Section 4 Build TJU longitudinal healthy control references
% Construct orientation specific TJU healthy control FC and NMR reference
% distributions for patient level normative standardization.

% Load healthy control metadata and allocate orientation specific arrays.

hc_metadata = readtable( ...
    fullfile(metadata_root, 'TJU_HC_metadata.xlsx'), ...
    'Sheet', 'TJU_HC_metadata', ...
    'VariableNamingRule', 'preserve');
hc_ids = upper(strtrim(string(hc_metadata.('Subject ID'))));
n_hc = numel(hc_ids);

hc_pre_fc = cell(n_hc, 2); % N_HC x 2 PRE FC matrices by orientation.
hc_post_fc = cell(n_hc, 2); % N_HC x 2 POST FC matrices by orientation.
hc_nmr_percent = nan(n_hc, n_rois, 2); % N_HC x 116 x 2 signed GMV change (%).
hc_ncr_original_tables = cell(n_hc, 1);
hc_nmr_original_tables = cell(n_hc, 1);

fprintf('Building longitudinal references from %d TJU healthy controls.\n', ...
    n_hc);

% Calculate individual HC FC and NMR values in both atlas orientations.
for hc_index = 1:n_hc
    subject_id = hc_ids(hc_index);
    feature_path = fullfile( ...
        feature_root, 'TJU', 'regional_features', ...
        subject_id + "_Regional_Features.mat");
    feature_data = load(feature_path);

    for orientation_index = 1:2
        [pre_time_series, post_time_series, pre_gmv, post_gmv] = ...
            select_regional_features(feature_data, orientation_index);
        % Build 116 by 116 Pearson FC matrices from time points by ROI BOLD
        % arrays. No row wise missing value omission is applied, so
        % nonfinite BOLD values propagate to the affected correlations.
        hc_pre_fc{hc_index, orientation_index} = ...
            corrcoef(pre_time_series);
        hc_post_fc{hc_index, orientation_index} = ...
            corrcoef(post_time_series);
        hc_pre_fc{hc_index, orientation_index}( ...
            1:n_rois + 1:end) = 1;
        hc_post_fc{hc_index, orientation_index}( ...
            1:n_rois + 1:end) = 1;

        hc_nmr_percent(hc_index, :, orientation_index) = ...
            (100 .* (post_gmv - pre_gmv) ./ pre_gmv)'; % Signed POST versus PRE GMV change (%).
    end

    % Calculate Original orientation HC NCR using all 115 nontarget profile
    % edges because healthy controls have no surgery affected ROIs.
    [profile_raw_r, ncr, n_profile_edges] = ...
        calculate_nodal_connectivity_reconfiguration( ...
        hc_pre_fc{hc_index, 1}, hc_post_fc{hc_index, 1}, ...
        roi_ids, zeros(0, 1));
    nmr_percent = squeeze(hc_nmr_percent(hc_index, :, 1))';

    hc_ncr_original_tables{hc_index} = table( ...
        repmat("TJU", n_rois, 1), ...
        repmat(subject_id, n_rois, 1), ...
        repmat("HC", n_rois, 1), ...
        repmat("", n_rois, 1), ...
        repmat("Original", n_rois, 1), ...
        repmat("Not_Applicable", n_rois, 1), ...
        roi_ids, roi_names, roi_networks, false(n_rois, 1), ...
        n_profile_edges, profile_raw_r, ncr, ...
        nan(n_rois, 1), nan(n_rois, 1), nan(n_rois, 1), ...
        'VariableNames', { ...
        'Dataset', 'Subject_ID', 'Group', 'TLE_Laterality', ...
        'Atlas_Orientation', 'Hemisphere_Interpretation', ...
        'ROI_ID', 'ROI_Name', 'Network', 'Surgery_Affected', ...
        'N_Profile_Edges', 'Profile_Raw_R', ...
        'Nodal_Connectivity_Reconfiguration', 'Normative_Z', ...
        'HC_Reference_Mean', 'HC_Reference_SD'});

    hc_nmr_original_tables{hc_index} = table( ...
        repmat("TJU", n_rois, 1), ...
        repmat(subject_id, n_rois, 1), ...
        repmat("HC", n_rois, 1), ...
        repmat("", n_rois, 1), ...
        repmat("Original", n_rois, 1), ...
        repmat("Not_Applicable", n_rois, 1), ...
        roi_ids, roi_names, roi_networks, false(n_rois, 1), ...
        feature_data.gmv_pre_original, ...
        feature_data.gmv_post_original, nmr_percent, ...
        nan(n_rois, 1), nan(n_rois, 1), nan(n_rois, 1), ...
        'VariableNames', { ...
        'Dataset', 'Subject_ID', 'Group', 'TLE_Laterality', ...
        'Atlas_Orientation', 'Hemisphere_Interpretation', ...
        'ROI_ID', 'ROI_Name', 'Network', 'Surgery_Affected', ...
        'Pre_GMV_mm3', 'Post_GMV_mm3', ...
        'Nodal_Morphometric_Reorganization_Percent', ...
        'Normative_Z', 'HC_Reference_Mean_Percent', ...
        'HC_Reference_SD_Percent'});
end

% Calculate orientation specific HC mean, sample SD, minimum, and maximum
% without NaN omission because the approved HC feature arrays are complete.
hc_nmr_mean = squeeze(mean(hc_nmr_percent, 1));
hc_nmr_sd = squeeze(std(hc_nmr_percent, 0, 1));
hc_nmr_minimum = squeeze(min(hc_nmr_percent, [], 1));
hc_nmr_maximum = squeeze(max(hc_nmr_percent, [], 1));

% Write the HC NMR reference distributions required by each analysis mode.
for mode_index = 1:2
    if analysis_modes(mode_index) == "Original"
        reference_orientation_indices = 1;
    else
        reference_orientation_indices = 1:2;
    end

    reference_table = table();
    for orientation_index = reference_orientation_indices
        current_table = table( ...
            repmat("TJU", n_rois, 1), ...
            repmat(analysis_modes(mode_index), n_rois, 1), ...
            repmat(orientation_labels(orientation_index), n_rois, 1), ...
            roi_ids, roi_names, roi_networks, ...
            hc_nmr_mean(:, orientation_index), ...
            hc_nmr_sd(:, orientation_index), ...
            hc_nmr_minimum(:, orientation_index), ...
            hc_nmr_maximum(:, orientation_index), ...
            hc_nmr_sd(:, orientation_index) > 0, ...
            'VariableNames', { ...
            'Dataset', 'Analysis_Mode', 'Atlas_Orientation', ...
            'ROI_ID', 'ROI_Name', 'Network', ...
            'HC_Reference_Mean_Percent', ...
            'HC_Reference_SD_Percent', ...
            'HC_Reference_Minimum_Percent', ...
            'HC_Reference_Maximum_Percent', 'Variance_Valid'});
        reference_table = [reference_table; current_table]; %#ok<AGROW>
    end
    writetable(reference_table, fullfile( ...
        result_dirs{1, mode_index}, 'HC_NMR_Reference.csv'));
end

%% Section 5 Calculate patient nodal reorganization for both centers
% Calculate patient level FC, NCR, NMR, surgery overlap provenance, and TJU
% normative Z scores in Original and Laterality_Normalized representations.

% Load center specific patient metadata and process both analysis modes.
for dataset_index = 1:2
    dataset = dataset_names(dataset_index);

    if dataset == "TJU"
        metadata = readtable( ...
            fullfile(metadata_root, 'TJU_metadata.xlsx'), ...
            'Sheet', 'TJU_metadata', ...
            'VariableNamingRule', 'preserve');
    else
        metadata = readtable( ...
            fullfile(metadata_root, 'JLH_metadata.xlsx'), ...
            'Sheet', 'JLH_metadata', ...
            'VariableNamingRule', 'preserve');
    end
    patient_ids = upper(strtrim(string(metadata.('Subject ID'))));
    patient_lateralities = upper(strtrim(string( ...
        metadata.('TLE laterality'))));
    n_patients = numel(patient_ids);

    for mode_index = 1:2
        analysis_mode = analysis_modes(mode_index);
        fprintf('Calculating %s reorganization for %d %s patients.\n', ...
            analysis_mode, n_patients, dataset);

        patient_ncr_tables = cell(n_patients, 1);
        patient_nmr_tables = cell(n_patients, 1);
        surgery_overlap_tables = cell(n_patients, 1);
        patient_reference_tables = cell(n_patients, 1);

        for patient_index = 1:n_patients
            subject_id = patient_ids(patient_index);
            tle_laterality = patient_lateralities(patient_index);
            group = "TLE";

            % Select the patient atlas orientation. Right TLE patients use
            % Flipped_LR only in Laterality_Normalized mode.
            if analysis_mode == "Original" || tle_laterality == "LEFT"
                orientation_index = 1;
            else
                orientation_index = 2;
            end
            atlas_orientation = orientation_labels(orientation_index);
            surgery_atlas_source = ...
                surgery_atlas_sources(orientation_index);
            bold_atlas_source = bold_atlas_sources(orientation_index);

            if analysis_mode == "Original"
                hemisphere_interpretation = anatomical_hemisphere;
            else
                hemisphere_interpretation = normalized_hemisphere;
            end

            fprintf('%s %s patient %d of %d: %s, %s\n', ...
                dataset, analysis_mode, patient_index, n_patients, ...
                subject_id, atlas_orientation);

            regional_feature_source = string(fullfile( ...
                'Data', dataset, 'regional_features', ...
                subject_id + "_Regional_Features.mat"));
            feature_data = load(fullfile( ...
                project_root, regional_feature_source));

            % Load the patient surgery overlap table and select the ROI order.
            surgery_overlap_source = string(fullfile( ...
                'Data', dataset, 'regional_features', ...
                subject_id + "_Surgery_ROI_Overlap.csv"));
            subject_overlap_table = readtable(fullfile( ...
                project_root, surgery_overlap_source), ...
                'VariableNamingRule', 'preserve', 'TextType', 'string');
            orientation_rows = string( ...
                subject_overlap_table.Atlas_Orientation) ...
                == atlas_orientation;
            current_overlap_table = ...
                subject_overlap_table(orientation_rows, :);
            [roi_found, roi_row_indices] = ismember( ...
                roi_ids, current_overlap_table.ROI_ID);
            if any(~roi_found) || height(current_overlap_table) ~= n_rois
                error( ...
                    'Block1:IncompleteSurgeryOverlap', ...
                    ['Expected one %s surgery overlap row for each ROI ' ...
                    'in %s.'], atlas_orientation, subject_id);
            end
            current_overlap_table = ...
                current_overlap_table(roi_row_indices, :);
            surgery_affected = logical( ...
                current_overlap_table.Surgery_Affected); % 116 x 1 excluded ROI and edge mask.
            partially_affected = logical( ...
                current_overlap_table.Partially_Affected); % 116 x 1 partial BOLD exclusion mask.
            surgery_affected_roi_ids = roi_ids(surgery_affected);

            if dataset == "TJU"
                surgery_mask_name = subject_id + ".nii.gz";
            else
                surgery_mask_name = ...
                    subject_id + "_POST1_Run1_ROI.nii.gz";
            end
            surgery_mask_1mm_source = string(fullfile( ...
                'Data', dataset, 'surgery_mask', 'Orig_1mm', ...
                surgery_mask_name));
            surgery_mask_bold_source = string(fullfile( ...
                'Data', dataset, 'surgery_mask', 'xcpd_2mm', ...
                surgery_mask_name));

            extraction_rule = repmat("Full_ROI", n_rois, 1);
            extraction_rule(partially_affected) = ...
                "Full_ROI_GMV_Partial_BOLD_Exclusion";
            extraction_rule(surgery_affected) = "Excluded_ROI";

            % Assemble one provenance row for each patient and ROI in the
            % current analysis mode.
            surgery_overlap_tables{patient_index} = table( ...
                repmat(dataset, n_rois, 1), ...
                repmat(analysis_mode, n_rois, 1), ...
                repmat(subject_id, n_rois, 1), ...
                repmat(tle_laterality, n_rois, 1), ...
                repmat(atlas_orientation, n_rois, 1), ...
                hemisphere_interpretation, ...
                repmat(surgery_atlas_source, n_rois, 1), ...
                repmat(bold_atlas_source, n_rois, 1), ...
                repmat(surgery_mask_1mm_source, n_rois, 1), ...
                repmat(surgery_mask_bold_source, n_rois, 1), ...
                roi_ids, roi_names, ...
                current_overlap_table.ROI_Voxel_Count, ...
                current_overlap_table.Intersection_Voxel_Count, ...
                current_overlap_table.Overlap_Percent, ...
                repmat(surgery_overlap_threshold_percent, ...
                n_rois, 1), partially_affected, surgery_affected, ...
                extraction_rule, ...
                'VariableNames', { ...
                'Dataset', 'Analysis_Mode', 'Subject_ID', ...
                'TLE_Laterality', 'Atlas_Orientation', ...
                'Hemisphere_Interpretation', 'Atlas_Source_1mm', ...
                'Atlas_Source_BOLD', 'Surgery_Mask_1mm', ...
                'Surgery_Mask_BOLD', 'ROI_ID', 'ROI_Name', ...
                'ROI_Voxel_Count', 'Intersection_Voxel_Count', ...
                'Overlap_Percent', 'Affected_Threshold_Percent', ...
                'Partially_Affected', 'Surgery_Affected', ...
                'Extraction_Rule'});

            % Select inherited regional features and prepare PRE and POST
            % session arrays for FC and GMV calculations.
            [pre_time_series, post_time_series, pre_gmv, post_gmv] = ...
                select_regional_features(feature_data, orientation_index);
            session_time_series = {pre_time_series; post_time_series};
            session_gmv = {pre_gmv; post_gmv};
            session_fc = cell(2, 1);
            for session_index = 1:2
                time_series = session_time_series{session_index};
                raw_fc = corrcoef(time_series); % 116 x 116 Pearson FC; nonfinite values propagate.
                raw_fc(1:n_rois + 1:end) = 1; % Set self correlations to one.
                session_fc{session_index} = raw_fc;
            end

            % Store the minimal numeric handoff used by downstream RDM
            % construction. ROI exclusions remain authoritative in the
            % surgery overlap table rather than being duplicated here.
            pre_raw_fc = session_fc{1};
            post_raw_fc = session_fc{2};
            pre_gmv_mm3 = session_gmv{1};
            post_gmv_mm3 = session_gmv{2};
            block2_input_path = fullfile( ...
                block2_input_dirs{dataset_index, mode_index}, ...
                subject_id + "_Block2_Input.mat");
            save(block2_input_path, ...
                'roi_ids', 'pre_raw_fc', 'post_raw_fc', ...
                'pre_gmv_mm3', 'post_gmv_mm3', '-v7.3');

            [profile_raw_r, ncr, n_profile_edges] = ...
                calculate_nodal_connectivity_reconfiguration( ...
                session_fc{1}, session_fc{2}, roi_ids, ...
                surgery_affected_roi_ids); % NCR = 1 minus PRE versus POST profile r; affected targets are NaN.
            nmr_percent = 100 .* ...
                (session_gmv{2} - session_gmv{1}) ./ session_gmv{1}; % Signed POST versus PRE GMV change (%).
            nmr_percent(surgery_affected) = NaN; % Exclude surgery affected ROIs.

            ncr_reference_mean = nan(n_rois, 1);
            ncr_reference_sd = nan(n_rois, 1);
            nmr_reference_mean = nan(n_rois, 1);
            nmr_reference_sd = nan(n_rois, 1);
            ncr_normative_z = nan(n_rois, 1);
            nmr_normative_z = nan(n_rois, 1);

            % For TJU only, standardize NCR using HC distributions calculated
            % from the same patient specific retained edge set. Standardize
            % NMR using the HC distribution for the selected atlas orientation.
            % Positive Z scores indicate greater change than the HC mean. JLH
            % reference and Z score fields remain NaN.
            if dataset == "TJU"
                patient_matched_hc_ncr = nan(n_hc, n_rois);
                for hc_index = 1:n_hc
                    [~, current_hc_ncr, ~] = ...
                        calculate_nodal_connectivity_reconfiguration( ...
                        hc_pre_fc{hc_index, orientation_index}, ...
                        hc_post_fc{hc_index, orientation_index}, ...
                        roi_ids, surgery_affected_roi_ids);
                    patient_matched_hc_ncr(hc_index, :) = ...
                        current_hc_ncr';
                end
                ncr_reference_mean = mean(patient_matched_hc_ncr, 1)';
                ncr_reference_sd = std(patient_matched_hc_ncr, 0, 1)';
                nmr_reference_mean = hc_nmr_mean(:, orientation_index);
                nmr_reference_sd = hc_nmr_sd(:, orientation_index);
                ncr_normative_z = ...
                    (ncr - ncr_reference_mean) ./ ncr_reference_sd;
                nmr_normative_z = ...
                    (nmr_percent - nmr_reference_mean) ...
                    ./ nmr_reference_sd;

                % Record the patient matched HC NCR distribution for each
                % patient and ROI.
                patient_reference_tables{patient_index} = table( ...
                    repmat(dataset, n_rois, 1), ...
                    repmat(analysis_mode, n_rois, 1), ...
                    repmat(subject_id, n_rois, 1), ...
                    repmat(tle_laterality, n_rois, 1), ...
                    repmat(atlas_orientation, n_rois, 1), ...
                    repmat(surgery_mask_1mm_source, ...
                    n_rois, 1), roi_ids, roi_names, surgery_affected, ...
                    n_profile_edges, ncr_reference_mean, ...
                    ncr_reference_sd, ...
                    min(patient_matched_hc_ncr, [], 1)', ...
                    max(patient_matched_hc_ncr, [], 1)', ...
                    ncr_reference_sd > 0, ...
                    'VariableNames', { ...
                    'Dataset', 'Analysis_Mode', 'Subject_ID', ...
                    'TLE_Laterality', 'Atlas_Orientation', ...
                    'Surgery_Mask_1mm', 'ROI_ID', 'ROI_Name', ...
                    'Surgery_Affected', 'N_Profile_Edges', ...
                    'HC_Reference_Mean', 'HC_Reference_SD', ...
                    'HC_Reference_Minimum', 'HC_Reference_Maximum', ...
                    'Variance_Valid'});
            end

            % Assemble one NCR row and one NMR row for each patient and ROI.
            % Subject level tables contain no inferential test results.
            patient_ncr_tables{patient_index} = table( ...
                repmat(dataset, n_rois, 1), ...
                repmat(subject_id, n_rois, 1), ...
                repmat(group, n_rois, 1), ...
                repmat(tle_laterality, n_rois, 1), ...
                repmat(atlas_orientation, n_rois, 1), ...
                hemisphere_interpretation, roi_ids, roi_names, ...
                roi_networks, surgery_affected, n_profile_edges, ...
                profile_raw_r, ncr, ncr_normative_z, ...
                ncr_reference_mean, ncr_reference_sd, ...
                'VariableNames', { ...
                'Dataset', 'Subject_ID', 'Group', 'TLE_Laterality', ...
                'Atlas_Orientation', 'Hemisphere_Interpretation', ...
                'ROI_ID', 'ROI_Name', 'Network', 'Surgery_Affected', ...
                'N_Profile_Edges', 'Profile_Raw_R', ...
                'Nodal_Connectivity_Reconfiguration', 'Normative_Z', ...
                'HC_Reference_Mean', 'HC_Reference_SD'});

            patient_nmr_tables{patient_index} = table( ...
                repmat(dataset, n_rois, 1), ...
                repmat(subject_id, n_rois, 1), ...
                repmat(group, n_rois, 1), ...
                repmat(tle_laterality, n_rois, 1), ...
                repmat(atlas_orientation, n_rois, 1), ...
                hemisphere_interpretation, roi_ids, roi_names, ...
                roi_networks, surgery_affected, session_gmv{1}, ...
                session_gmv{2}, nmr_percent, nmr_normative_z, ...
                nmr_reference_mean, nmr_reference_sd, ...
                'VariableNames', { ...
                'Dataset', 'Subject_ID', 'Group', 'TLE_Laterality', ...
                'Atlas_Orientation', 'Hemisphere_Interpretation', ...
                'ROI_ID', 'ROI_Name', 'Network', 'Surgery_Affected', ...
                'Pre_GMV_mm3', 'Post_GMV_mm3', ...
                'Nodal_Morphometric_Reorganization_Percent', ...
                'Normative_Z', 'HC_Reference_Mean_Percent', ...
                'HC_Reference_SD_Percent'});
        end

        % Combine patient rows with the approved TJU Original HC rows, then
        % write subject level, overlap, and reference tables.
        if dataset == "TJU" && analysis_mode == "Original"
            ncr_table_parts = [ ...
                hc_ncr_original_tables; patient_ncr_tables];
            nmr_table_parts = [ ...
                hc_nmr_original_tables; patient_nmr_tables];
        else
            ncr_table_parts = patient_ncr_tables;
            nmr_table_parts = patient_nmr_tables;
        end
        ncr_subject_table = vertcat(ncr_table_parts{:});
        nmr_subject_table = vertcat(nmr_table_parts{:});
        ncr_subject_table = addvars( ...
            ncr_subject_table, ...
            repmat(analysis_mode, height(ncr_subject_table), 1), ...
            'After', 'Dataset', 'NewVariableNames', 'Analysis_Mode');
        nmr_subject_table = addvars( ...
            nmr_subject_table, ...
            repmat(analysis_mode, height(nmr_subject_table), 1), ...
            'After', 'Dataset', 'NewVariableNames', 'Analysis_Mode');
        surgery_overlap_table = vertcat(surgery_overlap_tables{:});

        writetable(ncr_subject_table, fullfile( ...
            result_dirs{dataset_index, mode_index}, ...
            'Nodal_Connectivity_Reconfiguration.csv'));
        writetable(nmr_subject_table, fullfile( ...
            result_dirs{dataset_index, mode_index}, ...
            'Nodal_Morphometric_Reorganization.csv'));
        writetable(surgery_overlap_table, fullfile( ...
            result_dirs{dataset_index, mode_index}, ...
            'Surgery_ROI_Overlap.csv'));

        if dataset == "TJU"
            patient_reference_table = ...
                vertcat(patient_reference_tables{:});
            writetable(patient_reference_table, fullfile( ...
                result_dirs{dataset_index, mode_index}, ...
                'Patient_Matched_HC_NCR_Reference.csv'));
        end
    end

    % Generate center level cavity frequency and ROI involvement outputs from
    % the Original representation overlap table.
    original_overlap_table = readtable(fullfile( ...
        result_dirs{dataset_index, 1}, ...
        'Surgery_ROI_Overlap.csv'), ...
        'VariableNamingRule', 'preserve', 'TextType', 'string');
    write_surgical_cavity_frequency_outputs( ...
        string(project_root), dataset, ...
        string(original_surgery_atlas_file), ...
        original_overlap_table, n_patients);
end

fprintf('Nodal reorganization calculations completed for TJU and JLH.\n');
