% Step3_Run_Nodal_Reorganization_Statistics
%
% Purpose:
% This script creates the authoritative wide regional result tables for
% postoperative nodal connectivity reconfiguration and nodal morphometric
% reorganization. Original results are calculated separately for Left TLE
% and Right TLE. Laterality Normalized results use the pooled TLE cohort.
% TJU Normative Z scores are tested against zero with separate regional
% Benjamini Hochberg FDR families for NCR and NMR. JLH results are
% descriptive because longitudinal healthy controls are unavailable.
%
% The script also writes the TJU healthy control regional summary used by
% Step 4. Network summaries and network inference are outside the approved
% Block 1 result scope and are not calculated.
%
% Dependencies:
% 1. MATLAB with Statistics and Machine Learning Toolbox.
% 2. Bioinformatics Toolbox for mafdr.
% 3. Subject level regional results and surgery overlap tables from Step 2.
%
% Author: Qirui Zhang
% Created: 31 August 2026

clear;
clc;

%% Section 1 Set project configuration

this_file = mfilename('fullpath');
project_root = fileparts(fileparts(fileparts(fileparts(this_file))));
addpath(fullfile(project_root, 'src', 'utils'));

results_root = fullfile( ...
    project_root, 'results', 'Block1_TLE_surgery_reorganization');
analysis_modes = ["Original"; "Laterality_Normalized"];
alpha = 0.05;
minimum_patient_count = 10;

subject_string_columns = { ...
    'Dataset', 'Analysis_Mode', 'Subject_ID', 'Group', ...
    'TLE_Laterality', 'Atlas_Orientation', ...
    'Hemisphere_Interpretation', 'ROI_Name', 'Network'};
overlap_string_columns = { ...
    'Dataset', 'Analysis_Mode', 'Subject_ID', ...
    'TLE_Laterality', 'ROI_Name'};

for mode_index = 1:numel(analysis_modes)
    analysis_mode = analysis_modes(mode_index);
    tju_result_dir = fullfile(results_root, 'TJU', analysis_mode);
    jlh_result_dir = fullfile(results_root, 'JLH', analysis_mode);

    %% Section 2 Read fixed Step 2 regional results

    tju_ncr_file = fullfile( ...
        tju_result_dir, 'Nodal_Connectivity_Reconfiguration.csv');
    tju_nmr_file = fullfile( ...
        tju_result_dir, 'Nodal_Morphometric_Reorganization.csv');
    jlh_ncr_file = fullfile( ...
        jlh_result_dir, 'Nodal_Connectivity_Reconfiguration.csv');
    jlh_nmr_file = fullfile( ...
        jlh_result_dir, 'Nodal_Morphometric_Reorganization.csv');

    subject_level_files = { ...
        tju_ncr_file; tju_nmr_file; jlh_ncr_file; jlh_nmr_file};
    subject_level_tables = cell(4, 1);

    for input_index = 1:numel(subject_level_files)
        import_options = detectImportOptions( ...
            subject_level_files{input_index}, ...
            'VariableNamingRule', 'preserve', ...
            'TextType', 'string');
        import_options = setvartype( ...
            import_options, subject_string_columns, 'string');
        subject_level_tables{input_index} = readtable( ...
            subject_level_files{input_index}, import_options);
    end

    tju_ncr_table = subject_level_tables{1};
    tju_nmr_table = subject_level_tables{2};
    jlh_ncr_table = subject_level_tables{3};
    jlh_nmr_table = subject_level_tables{4};

    %% Section 3 Read fixed surgery overlap tables

    tju_overlap_file = fullfile( ...
        tju_result_dir, ...
        'Surgery_ROI_Overlap.csv');
    jlh_overlap_file = fullfile( ...
        jlh_result_dir, ...
        'Surgery_ROI_Overlap.csv');

    tju_overlap_options = detectImportOptions( ...
        tju_overlap_file, ...
        'VariableNamingRule', 'preserve', 'TextType', 'string');
    tju_overlap_options = setvartype( ...
        tju_overlap_options, overlap_string_columns, 'string');
    tju_overlap_table = readtable(tju_overlap_file, tju_overlap_options);

    jlh_overlap_options = detectImportOptions( ...
        jlh_overlap_file, ...
        'VariableNamingRule', 'preserve', 'TextType', 'string');
    jlh_overlap_options = setvartype( ...
        jlh_overlap_options, overlap_string_columns, 'string');
    jlh_overlap_table = readtable(jlh_overlap_file, jlh_overlap_options);

    %% Section 4 Generate group cavity masks

    % An ROI is group masked when surgery affected at least one patient in
    % the applicable cohort and laterality group.
    if analysis_mode == "Original"
        tju_left_mask = generate_group_cavity_mask( ...
            tju_overlap_table, "TJU", analysis_mode, "LEFT");
        tju_right_mask = generate_group_cavity_mask( ...
            tju_overlap_table, "TJU", analysis_mode, "RIGHT");
        jlh_left_mask = generate_group_cavity_mask( ...
            jlh_overlap_table, "JLH", analysis_mode, "LEFT");
        jlh_right_mask = generate_group_cavity_mask( ...
            jlh_overlap_table, "JLH", analysis_mode, "RIGHT");

        writetable( ...
            [tju_left_mask; tju_right_mask], ...
            fullfile(tju_result_dir, ...
            'Group_Surgery_Affected_ROIs.csv'));
        writetable( ...
            [jlh_left_mask; jlh_right_mask], ...
            fullfile(jlh_result_dir, ...
            'Group_Surgery_Affected_ROIs.csv'));
    else
        tju_pooled_mask = generate_group_cavity_mask( ...
            tju_overlap_table, "TJU", analysis_mode, "ALL");
        jlh_pooled_mask = generate_group_cavity_mask( ...
            jlh_overlap_table, "JLH", analysis_mode, "ALL");

        writetable( ...
            tju_pooled_mask, ...
            fullfile(tju_result_dir, ...
            'Group_Surgery_Affected_ROIs.csv'));
        writetable( ...
            jlh_pooled_mask, ...
            fullfile(jlh_result_dir, ...
            'Group_Surgery_Affected_ROIs.csv'));
    end

    %% Section 5 Calculate authoritative regional results

    % Raw NCR and NMR summaries use every finite nonaffected patient value.
    % TJU inference uses a separate Normative Z validity mask and requires at
    % least 10 valid patients for each one sample two sided t test.
    if analysis_mode == "Original"
        tju_left_results = ...
            calculate_nodal_reorganization_regional_results( ...
            tju_ncr_table, tju_nmr_table, tju_left_mask, ...
            "TJU", analysis_mode, "LEFT", ...
            minimum_patient_count, alpha, true);
        tju_right_results = ...
            calculate_nodal_reorganization_regional_results( ...
            tju_ncr_table, tju_nmr_table, tju_right_mask, ...
            "TJU", analysis_mode, "RIGHT", ...
            minimum_patient_count, alpha, true);
        jlh_left_results = ...
            calculate_nodal_reorganization_regional_results( ...
            jlh_ncr_table, jlh_nmr_table, jlh_left_mask, ...
            "JLH", analysis_mode, "LEFT", ...
            minimum_patient_count, alpha, false);
        jlh_right_results = ...
            calculate_nodal_reorganization_regional_results( ...
            jlh_ncr_table, jlh_nmr_table, jlh_right_mask, ...
            "JLH", analysis_mode, "RIGHT", ...
            minimum_patient_count, alpha, false);

        writetable( ...
            tju_left_results, ...
            fullfile(tju_result_dir, ...
            'Left_TLE_Nodal_Reorganization_Regional_Results.csv'));
        writetable( ...
            tju_right_results, ...
            fullfile(tju_result_dir, ...
            'Right_TLE_Nodal_Reorganization_Regional_Results.csv'));
        writetable( ...
            jlh_left_results, ...
            fullfile(jlh_result_dir, ...
            'Left_TLE_Nodal_Reorganization_Regional_Results.csv'));
        writetable( ...
            jlh_right_results, ...
            fullfile(jlh_result_dir, ...
            'Right_TLE_Nodal_Reorganization_Regional_Results.csv'));

        %% Section 6 Calculate TJU healthy control regional summary

        hc_summary = calculate_nodal_reorganization_hc_summary( ...
            tju_ncr_table, tju_nmr_table);
        writetable( ...
            hc_summary, ...
            fullfile(tju_result_dir, ...
            'HC_Nodal_Reorganization_Regional_Summary.csv'));
    else
        tju_results = ...
            calculate_nodal_reorganization_regional_results( ...
            tju_ncr_table, tju_nmr_table, tju_pooled_mask, ...
            "TJU", analysis_mode, "ALL", ...
            minimum_patient_count, alpha, true);
        jlh_results = ...
            calculate_nodal_reorganization_regional_results( ...
            jlh_ncr_table, jlh_nmr_table, jlh_pooled_mask, ...
            "JLH", analysis_mode, "ALL", ...
            minimum_patient_count, alpha, false);

        writetable( ...
            tju_results, ...
            fullfile(tju_result_dir, ...
            'Nodal_Reorganization_Regional_Results.csv'));
        writetable( ...
            jlh_results, ...
            fullfile(jlh_result_dir, ...
            'Nodal_Reorganization_Regional_Results.csv'));
    end

    fprintf('Regional nodal reorganization statistics completed for %s.\n', ...
        analysis_mode);
end

fprintf('Step 3 regional statistics completed.\n');
