% Step4_Plot_Nodal_Reorganization_Maps
%
% Purpose:
% This script generates the approved regional maps and cross center spatial
% correlation results for postoperative nodal connectivity reconfiguration
% and nodal morphometric reorganization. It reads the authoritative wide
% regional result tables from Step 3. TJU maps include raw means, mean
% Normative Z values, and FDR masked mean Normative Z values. JLH maps
% include raw means only. TJU healthy control mean and standard deviation
% maps are generated from the Step 3 healthy control regional summary.
%
% The script writes cortical and subcortical ENIGMA component figures,
% volumetric NIfTI maps, and the Laterality Normalized cross center Pearson
% spatial correlations. Nodal reorganization network calculations and
% network figures are outside the approved result scope.
%
% Required software:
% 1. MATLAB.
% 2. ENIGMA Toolbox 2.0.0 configured on the MATLAB path.
%
% Author: Qirui Zhang
% Created: 31 August 2026

clear;
clc;

%% Section 1 Set project configuration

this_file = mfilename('fullpath');
project_root = fileparts(fileparts(fileparts(fileparts(this_file))));
addpath(fullfile(project_root, 'src', 'utils'));

block_name = 'Block1_TLE_surgery_reorganization';
results_root = fullfile(project_root, 'results', block_name);
analysis_modes = ["Original"; "Laterality_Normalized"];
dataset_names = ["TJU"; "JLH"];

mapping_file = fullfile( ...
    project_root, 'Data', 'atlas', ...
    'cocoyeo143_to_ENIGMA_schaefer100_mapping.csv');
atlas_file = fullfile( ...
    project_root, 'Data', 'atlas', ...
    'cocoyeo143_dil2_allsubj_mode.nii.gz');

metric_ncr = "Nodal_Connectivity_Reconfiguration";
metric_nmr = "Nodal_Morphometric_Reorganization_Percent";
subcortical_enigma_roi_ids = ...
    [7; 6; 2; 5; 4; 3; 1; 15; 14; 10; 13; 12; 11; 9];

regional_string_columns = { ...
    'Dataset', 'Analysis_Mode', 'Group', ...
    'TLE_Laterality', 'ROI_Name', 'Network'};
hc_string_columns = { ...
    'Dataset', 'Analysis_Mode', 'Group', 'ROI_Name', 'Network'};

%% Section 2 Create output directories

for mode_index = 1:numel(analysis_modes)
    analysis_mode = analysis_modes(mode_index);

    for dataset_index = 1:numel(dataset_names)
        dataset_root = fullfile( ...
            results_root, dataset_names(dataset_index), analysis_mode);
        enigma_input_dir = fullfile( ...
            dataset_root, 'enigma_inputs');
        figure_dir = fullfile(dataset_root, 'figures');

        if ~isfolder(enigma_input_dir)
            mkdir(enigma_input_dir);
        end
        if ~isfolder(figure_dir)
            mkdir(figure_dir);
        end
    end
end

%% Section 3 Read fixed atlas resources

mapping_table = readtable( ...
    mapping_file, 'VariableNamingRule', 'preserve');
atlas_info = niftiinfo(atlas_file);
atlas_data = niftiread(atlas_info);
atlas_info.Datatype = 'single';
atlas_info.BitsPerPixel = 32;

%% Section 4 Define map color ranges

ncr_raw_color_range = [0.4, 0.8];
nmr_raw_color_range = [-15, 15];
ncr_z_color_range = [-1, 1];
nmr_z_color_range = [-1.5, 1.5];

hc_summary_file = fullfile( ...
    results_root, 'TJU', 'Original', ...
    'HC_Nodal_Reorganization_Regional_Summary.csv');
hc_import_options = detectImportOptions( ...
    hc_summary_file, ...
    'VariableNamingRule', 'preserve', 'TextType', 'string');
hc_import_options = setvartype( ...
    hc_import_options, hc_string_columns, 'string');
hc_summary = readtable(hc_summary_file, hc_import_options);
hc_ncr_sd_color_range = [ ...
    0, max(hc_summary.NCR_SD_Raw, [], 'omitnan')];
hc_nmr_sd_color_range = [ ...
    0, max(hc_summary.NMR_SD_Raw_Percent, [], 'omitnan')];

%% Section 5 Build and write regional maps

for mode_index = 1:numel(analysis_modes)
    analysis_mode = analysis_modes(mode_index);
    tju_mode_root = fullfile(results_root, 'TJU', analysis_mode);
    jlh_mode_root = fullfile(results_root, 'JLH', analysis_mode);

    %% Section 5.1 Read authoritative regional result tables

    if analysis_mode == "Original"
        tju_left_file = fullfile( ...
            tju_mode_root, ...
            'Left_TLE_Nodal_Reorganization_Regional_Results.csv');
        tju_right_file = fullfile( ...
            tju_mode_root, ...
            'Right_TLE_Nodal_Reorganization_Regional_Results.csv');
        jlh_left_file = fullfile( ...
            jlh_mode_root, ...
            'Left_TLE_Nodal_Reorganization_Regional_Results.csv');
        jlh_right_file = fullfile( ...
            jlh_mode_root, ...
            'Right_TLE_Nodal_Reorganization_Regional_Results.csv');

        tju_import_options = detectImportOptions( ...
            tju_left_file, ...
            'VariableNamingRule', 'preserve', 'TextType', 'string');
        tju_import_options = setvartype( ...
            tju_import_options, regional_string_columns, 'string');
        jlh_import_options = detectImportOptions( ...
            jlh_left_file, ...
            'VariableNamingRule', 'preserve', 'TextType', 'string');
        jlh_import_options = setvartype( ...
            jlh_import_options, regional_string_columns, 'string');

        tju_results = [ ...
            readtable(tju_left_file, tju_import_options); ...
            readtable(tju_right_file, tju_import_options)];
        jlh_results = [ ...
            readtable(jlh_left_file, jlh_import_options); ...
            readtable(jlh_right_file, jlh_import_options)];
    else
        tju_result_file = fullfile( ...
            tju_mode_root, ...
            'Nodal_Reorganization_Regional_Results.csv');
        jlh_result_file = fullfile( ...
            jlh_mode_root, ...
            'Nodal_Reorganization_Regional_Results.csv');

        tju_import_options = detectImportOptions( ...
            tju_result_file, ...
            'VariableNamingRule', 'preserve', 'TextType', 'string');
        tju_import_options = setvartype( ...
            tju_import_options, regional_string_columns, 'string');
        jlh_import_options = detectImportOptions( ...
            jlh_result_file, ...
            'VariableNamingRule', 'preserve', 'TextType', 'string');
        jlh_import_options = setvartype( ...
            jlh_import_options, regional_string_columns, 'string');

        tju_results = readtable(tju_result_file, tju_import_options);
        jlh_results = readtable(jlh_result_file, jlh_import_options);
        tju_laterality_normalized_results = tju_results;
        jlh_laterality_normalized_results = jlh_results;
    end

    %% Section 5.2 Define the approved maps

    if analysis_mode == "Original"
        map_dataset = [ ...
            repmat("TJU", 12, 1); ...
            repmat("JLH", 4, 1); ...
            repmat("TJU_HC", 4, 1)];
        map_laterality = [ ...
            repmat("LEFT", 6, 1); ...
            repmat("RIGHT", 6, 1); ...
            repmat("LEFT", 2, 1); ...
            repmat("RIGHT", 2, 1); ...
            repmat("ALL", 4, 1)];
        map_metric = [ ...
            repmat([metric_ncr; metric_nmr], 6, 1); ...
            repmat([metric_ncr; metric_nmr], 4, 1)];
        map_value_field = [ ...
            repmat([ ...
                "NCR_Mean_Raw"; ...
                "NMR_Mean_Raw_Percent"; ...
                "NCR_Mean_Normative_Z"; ...
                "NMR_Mean_Normative_Z"; ...
                "NCR_Mean_Normative_Z"; ...
                "NMR_Mean_Normative_Z"], 2, 1); ...
            repmat([ ...
                "NCR_Mean_Raw"; ...
                "NMR_Mean_Raw_Percent"], 2, 1); ...
            "NCR_Mean_Raw"; ...
            "NMR_Mean_Raw_Percent"; ...
            "NCR_SD_Raw"; ...
            "NMR_SD_Raw_Percent"];
        map_fdr_field = [ ...
            repmat([""; ""; ""; ""; "NCR_FDR_P"; "NMR_FDR_P"], 2, 1); ...
            repmat("", 8, 1)];
        map_output_name = [ ...
            "Left_TLE_Mean_Nodal_Connectivity_Reconfiguration"; ...
            "Left_TLE_Mean_Nodal_Morphometric_Reorganization_Percent"; ...
            "Left_TLE_Mean_Z_Nodal_Connectivity_Reconfiguration"; ...
            "Left_TLE_Mean_Z_Nodal_Morphometric_Reorganization_Percent"; ...
            "Left_TLE_Mean_Z_Nodal_Connectivity_Reconfiguration_FDR"; ...
            "Left_TLE_Mean_Z_Nodal_Morphometric_Reorganization_Percent_FDR"; ...
            "Right_TLE_Mean_Nodal_Connectivity_Reconfiguration"; ...
            "Right_TLE_Mean_Nodal_Morphometric_Reorganization_Percent"; ...
            "Right_TLE_Mean_Z_Nodal_Connectivity_Reconfiguration"; ...
            "Right_TLE_Mean_Z_Nodal_Morphometric_Reorganization_Percent"; ...
            "Right_TLE_Mean_Z_Nodal_Connectivity_Reconfiguration_FDR"; ...
            "Right_TLE_Mean_Z_Nodal_Morphometric_Reorganization_Percent_FDR"; ...
            "Left_TLE_Mean_Nodal_Connectivity_Reconfiguration"; ...
            "Left_TLE_Mean_Nodal_Morphometric_Reorganization_Percent"; ...
            "Right_TLE_Mean_Nodal_Connectivity_Reconfiguration"; ...
            "Right_TLE_Mean_Nodal_Morphometric_Reorganization_Percent"; ...
            "HC_Mean_Nodal_Connectivity_Reconfiguration"; ...
            "HC_Mean_Nodal_Morphometric_Reorganization_Percent"; ...
            "HC_SD_Nodal_Connectivity_Reconfiguration"; ...
            "HC_SD_Nodal_Morphometric_Reorganization_Percent"];
    else
        map_dataset = [repmat("TJU", 6, 1); repmat("JLH", 2, 1)];
        map_laterality = repmat("ALL", 8, 1);
        map_metric = repmat([metric_ncr; metric_nmr], 4, 1);
        map_value_field = [ ...
            "NCR_Mean_Raw"; ...
            "NMR_Mean_Raw_Percent"; ...
            "NCR_Mean_Normative_Z"; ...
            "NMR_Mean_Normative_Z"; ...
            "NCR_Mean_Normative_Z"; ...
            "NMR_Mean_Normative_Z"; ...
            "NCR_Mean_Raw"; ...
            "NMR_Mean_Raw_Percent"];
        map_fdr_field = [ ...
            ""; ""; ""; ""; "NCR_FDR_P"; "NMR_FDR_P"; ""; ""];
        map_output_name = [ ...
            "Mean_Nodal_Connectivity_Reconfiguration"; ...
            "Mean_Nodal_Morphometric_Reorganization_Percent"; ...
            "Mean_Z_Nodal_Connectivity_Reconfiguration"; ...
            "Mean_Z_Nodal_Morphometric_Reorganization_Percent"; ...
            "Mean_Z_Nodal_Connectivity_Reconfiguration_FDR"; ...
            "Mean_Z_Nodal_Morphometric_Reorganization_Percent_FDR"; ...
            "Mean_Nodal_Connectivity_Reconfiguration"; ...
            "Mean_Nodal_Morphometric_Reorganization_Percent"];
    end

    %% Section 5.3 Write map inputs and component figures

    for map_index = 1:numel(map_output_name)
        current_dataset = map_dataset(map_index);
        current_metric = map_metric(map_index);
        current_value_field = map_value_field(map_index);
        current_fdr_field = map_fdr_field(map_index);
        current_output_name = map_output_name(map_index);

        if current_dataset == "TJU"
            current_table = tju_results;
            output_dataset = "TJU";
        elseif current_dataset == "JLH"
            current_table = jlh_results;
            output_dataset = "JLH";
        else
            current_table = hc_summary;
            output_dataset = "TJU";
        end

        current_rows = true(height(current_table), 1);
        if analysis_mode == "Original" && current_dataset ~= "TJU_HC"
            current_rows = ...
                upper(string(current_table.TLE_Laterality)) == ...
                map_laterality(map_index);
        end

        current_roi_ids = current_table.ROI_ID(current_rows);
        current_roi_names = string(current_table.ROI_Name(current_rows));
        current_values = current_table.(char(current_value_field))(current_rows);
        if current_dataset == "TJU_HC"
            current_masked = false(sum(current_rows), 1);
        else
            current_masked = logical(current_table.Group_Masked(current_rows));
        end

        % FDR component maps display the mean Normative Z value only where
        % the corresponding regional FDR adjusted P value is below 0.05.
        if current_fdr_field ~= ""
            current_fdr_p = ...
                current_table.(char(current_fdr_field))(current_rows);
            current_values( ...
                ~isfinite(current_fdr_p) | current_fdr_p >= 0.05) = NaN;
        end

        if contains(current_value_field, "SD") && ...
                current_metric == metric_ncr
            current_color_range = hc_ncr_sd_color_range;
            current_colormap = 'Blues';
        elseif contains(current_value_field, "SD")
            current_color_range = hc_nmr_sd_color_range;
            current_colormap = 'Blues';
        elseif contains(current_value_field, "Normative_Z") && ...
                current_metric == metric_ncr
            current_color_range = ncr_z_color_range;
            current_colormap = 'RdBu_r';
        elseif contains(current_value_field, "Normative_Z")
            current_color_range = nmr_z_color_range;
            current_colormap = 'RdBu_r';
        elseif current_metric == metric_ncr
            current_color_range = ncr_raw_color_range;
            current_colormap = 'Reds';
        else
            current_color_range = nmr_raw_color_range;
            current_colormap = 'RdBu_r';
        end

        dataset_root = fullfile( ...
            results_root, output_dataset, analysis_mode);
        enigma_input_dir = fullfile( ...
            dataset_root, 'enigma_inputs');
        figure_dir = fullfile(dataset_root, 'figures');

        %% Section 5.3.1 Write the Schaefer100 input table

        [~, cortical_row_indices] = ismember( ...
            mapping_table.Project_ROI_ID, current_roi_ids);
        cortical_values = current_values(cortical_row_indices);
        cortical_mask = current_masked(cortical_row_indices);
        cortical_roi_names = current_roi_names(cortical_row_indices);
        cortical_hemisphere = repmat("Right", height(mapping_table), 1);
        cortical_hemisphere(startsWith( ...
            string(mapping_table.ENIGMA_Name), "7Networks_LH")) = "Left";
        if analysis_mode == "Original"
            cortical_hemisphere_interpretation = ...
                "Anatomical_" + cortical_hemisphere;
        else
            cortical_hemisphere_interpretation = repmat( ...
                "Contralateral", height(mapping_table), 1);
            cortical_hemisphere_interpretation( ...
                cortical_hemisphere == "Left") = "Ipsilateral";
        end

        cortical_output_table = table( ...
            mapping_table.ENIGMA_Index, cortical_hemisphere, ...
            cortical_hemisphere_interpretation, ...
            mapping_table.Project_ROI_ID, cortical_roi_names, ...
            cortical_values, cortical_mask, ...
            'VariableNames', { ...
            'ENIGMA_Index', 'Hemisphere', ...
            'Hemisphere_Interpretation', 'Atlas_ROI_ID', ...
            'ROI_Name', 'Map_Value', 'Masked'});
        writetable( ...
            cortical_output_table, ...
            fullfile(enigma_input_dir, ...
            char(current_output_name + "_Schaefer100.csv")));

        %% Section 5.3.2 Write the subcortical input table

        subcortical_roi_ids = (1:16)';
        [~, subcortical_row_indices] = ismember( ...
            subcortical_roi_ids, current_roi_ids);
        subcortical_values_all = current_values(subcortical_row_indices);
        subcortical_mask_all = current_masked(subcortical_row_indices);
        subcortical_roi_names = current_roi_names(subcortical_row_indices);
        subcortical_hemisphere = repmat("Right", 16, 1);
        subcortical_hemisphere(startsWith( ...
            subcortical_roi_names, "Left")) = "Left";
        if analysis_mode == "Original"
            subcortical_hemisphere_interpretation = ...
                "Anatomical_" + subcortical_hemisphere;
        else
            subcortical_hemisphere_interpretation = ...
                repmat("Contralateral", 16, 1);
            subcortical_hemisphere_interpretation( ...
                subcortical_hemisphere == "Left") = "Ipsilateral";
        end

        subcortical_enigma_order = nan(16, 1);
        [~, enigma_order_indices] = ismember( ...
            subcortical_roi_ids, subcortical_enigma_roi_ids);
        supported_subcortical = enigma_order_indices > 0;
        subcortical_enigma_order(supported_subcortical) = ...
            enigma_order_indices(supported_subcortical);

        subcortical_output_table = table( ...
            subcortical_roi_ids, subcortical_roi_names, ...
            subcortical_hemisphere, ...
            subcortical_hemisphere_interpretation, ...
            subcortical_enigma_order, subcortical_values_all, ...
            subcortical_mask_all, supported_subcortical, ...
            'VariableNames', { ...
            'Atlas_ROI_ID', 'ROI_Name', 'Hemisphere', ...
            'Hemisphere_Interpretation', 'ENIGMA_Order', ...
            'Map_Value', 'Masked', 'Visualization_Supported'});
        writetable( ...
            subcortical_output_table, ...
            fullfile(enigma_input_dir, ...
            char(current_output_name + "_Subcortical.csv")));

        %% Section 5.3.3 Write the volumetric NIfTI map

        volume_data = zeros(size(atlas_data), 'single');
        for roi_index = 1:numel(current_roi_ids)
            if ~current_masked(roi_index) && ...
                    isfinite(current_values(roi_index))
                volume_data(atlas_data == current_roi_ids(roi_index)) = ...
                    single(current_values(roi_index));
            end
        end
        niftiwrite( ...
            volume_data, ...
            fullfile(enigma_input_dir, ...
            char(current_output_name + ".nii")), ...
            atlas_info, 'Compressed', true);

        if contains(current_value_field, "Normative_Z")
            current_colorbar_label = "Normative Z";
        elseif contains(current_value_field, "SD")
            current_colorbar_label = "Standard Deviation";
        elseif current_metric == metric_ncr
            current_colorbar_label = "NCR (1 minus r)";
        else
            current_colorbar_label = "NMR (%)";
        end

        %% Section 5.3.4 Render the cortical ENIGMA component

        cortical_figure = figure( ...
            'Visible', 'off', 'Color', 'white');
        plot_cortical_overlay( ...
            cortical_values, cortical_mask, ...
            'surface_name', 'conte69', ...
            'color_range', current_color_range, ...
            'cmap', current_colormap, ...
            'label_text', current_colorbar_label);
        print( ...
            cortical_figure, ...
            fullfile(figure_dir, ...
            char(current_output_name + "_Cortical.tiff")), ...
            '-dtiff', '-r300');
        close(cortical_figure);

        %% Section 5.3.5 Render the subcortical ENIGMA component

        [~, subcortical_plot_indices] = ismember( ...
            subcortical_enigma_roi_ids, current_roi_ids);
        subcortical_plot_values = current_values(subcortical_plot_indices);
        subcortical_plot_mask = current_masked(subcortical_plot_indices);
        subcortical_figure = figure( ...
            'Visible', 'off', 'Color', 'white');
        plot_subcortical_overlay( ...
            subcortical_plot_values, subcortical_plot_mask, ...
            'ventricles', 'False', ...
            'color_range', current_color_range, ...
            'cmap', current_colormap, ...
            'label_text', current_colorbar_label);
        print( ...
            subcortical_figure, ...
            fullfile(figure_dir, ...
            char(current_output_name + "_Subcortical.tiff")), ...
            '-dtiff', '-r300');
        close(subcortical_figure);
    end
end

%% Section 6 Calculate and plot cross center spatial correlations

correlation_metrics = [metric_ncr; metric_nmr];
correlation_raw_fields = [ ...
    "NCR_Mean_Raw"; "NMR_Mean_Raw_Percent"];
correlation_file_suffixes = ["NCR.tiff"; "NMR_Percent.tiff"];
correlation_colors = [0.75, 0.10, 0.10; 0.20, 0.40, 0.70];
n_correlation_rows = numel(correlation_metrics);

correlation_analysis_mode = ...
    repmat("Laterality_Normalized", n_correlation_rows, 1);
correlation_n_rois = zeros(n_correlation_rows, 1);
correlation_r = nan(n_correlation_rows, 1);
correlation_p = nan(n_correlation_rows, 1);
correlation_slope = nan(n_correlation_rows, 1);
correlation_intercept = nan(n_correlation_rows, 1);

% Pair centers by atlas ROI identity rather than relying on CSV row order.
% The fixed input contract provides one row per ROI and identical ROI sets.
[~, jlh_roi_order] = ismember( ...
    tju_laterality_normalized_results.ROI_ID, ...
    jlh_laterality_normalized_results.ROI_ID);

for metric_index = 1:n_correlation_rows
    current_metric = correlation_metrics(metric_index);
    current_raw_field = correlation_raw_fields(metric_index);

    x_values = tju_laterality_normalized_results.( ...
        char(current_raw_field));
    y_values = jlh_laterality_normalized_results.( ...
        char(current_raw_field));
    y_values = y_values(jlh_roi_order);
    tju_masked = logical( ...
        tju_laterality_normalized_results.Group_Masked);
    jlh_masked = logical( ...
        jlh_laterality_normalized_results.Group_Masked);
    jlh_masked = jlh_masked(jlh_roi_order);

    % Every ROI outside both cohort specific group masks enters the spatial
    % correlation. A nonfinite raw mean outside the masks is a fixed input
    % problem and stops the analysis rather than changing the ROI set.
    unmasked_pair = ~tju_masked & ~jlh_masked;
    if any(~isfinite(x_values(unmasked_pair))) || ...
            any(~isfinite(y_values(unmasked_pair)))
        error( ...
            'Step4:NonfiniteCrossCenterRawMean', ...
            ['A cross center raw mean is nonfinite outside the ' ...
            'group masks for %s.'], ...
            current_metric);
    end
    x_values = x_values(unmasked_pair);
    y_values = y_values(unmasked_pair);

    current_r = corr(x_values, y_values, 'Type', 'Pearson');
    current_degrees_freedom = numel(x_values) - 2;

    % Use the equivalent beta distribution form of the two-sided Pearson
    % test to preserve very small nonzero P values.
    current_p = betainc( ...
        1 - current_r ^ 2, current_degrees_freedom / 2, 0.5);
    fit_coefficients = polyfit(x_values, y_values, 1);
    fit_x = linspace(min(x_values), max(x_values), 100);
    fit_y = polyval(fit_coefficients, fit_x);

    correlation_n_rois(metric_index) = numel(x_values);
    correlation_r(metric_index) = current_r;
    correlation_p(metric_index) = current_p;
    correlation_slope(metric_index) = fit_coefficients(1);
    correlation_intercept(metric_index) = fit_coefficients(2);

    correlation_figure = figure( ...
        'Visible', 'off', 'Color', 'white', ...
        'Position', [100, 100, 650, 600]);
    scatter( ...
        x_values, y_values, 45, correlation_colors(metric_index, :), ...
        'filled', 'MarkerFaceAlpha', 0.75);
    hold on;
    plot(fit_x, fit_y, 'k-', 'LineWidth', 2);
    box on;
    set(gca, ...
        'Position', [0.15, 0.14, 0.75, 0.72], ...
        'FontName', 'Arial', 'FontSize', 12);
    xlabel('TJU mean', 'FontName', 'Arial', 'FontSize', 12);
    ylabel('JLH mean', 'FontName', 'Arial', 'FontSize', 12);
    title_handle = title( ...
        replace( ...
        "Laterality_Normalized: " + current_metric, "_", " "), ...
        'FontName', 'Arial', 'FontSize', 13, 'FontWeight', 'bold');
    set(title_handle, 'Units', 'normalized');
    title_position = get(title_handle, 'Position');
    set(title_handle, 'Position', ...
        [title_position(1), 1.04, title_position(3)]);

    p_text = sprintf('P = %.2e', current_p);
    statistics_text = sprintf( ...
        'r = %.3f\n%s\nN = %d', ...
        current_r, p_text, numel(x_values));
    text( ...
        0.05, 0.95, statistics_text, ...
        'Units', 'normalized', 'VerticalAlignment', 'top', ...
        'FontName', 'Arial', 'FontSize', 12, ...
        'Interpreter', 'tex');

    print( ...
        correlation_figure, ...
        fullfile(results_root, ...
        char( ...
        "Cross_Center_Laterality_Normalized_Spatial_Correlation_" + ...
        correlation_file_suffixes(metric_index))), ...
        '-dtiff', '-r300');
    close(correlation_figure);
end

correlation_table = table( ...
    correlation_analysis_mode, correlation_metrics, ...
    correlation_n_rois, ...
    correlation_r, correlation_p, ...
    correlation_slope, correlation_intercept, ...
    'VariableNames', { ...
    'Analysis_Mode', 'Metric', 'N_ROIs_Paired', ...
    'Pearson_R', 'Pearson_P', ...
    'Regression_Slope', 'Regression_Intercept'});
writetable( ...
    correlation_table, ...
    fullfile(results_root, ...
    'Cross_Center_Laterality_Normalized_Spatial_Correlation_Statistics.csv'));

fprintf('Step 4 regional map generation completed.\n');
