% Step1_Analyze_Pre_Post_Cognition: Analyze Pre- to Post-Surgical Cognitive Changes
%
% Purpose:
% Quantify longitudinal changes across 13 neuropsychological measures in the
% TJU cohort using complete paired observations and generate the corresponding
% statistical tables and standardized paired plot.
%
% Author: Qirui Zhang
% Creation Date: 2026-08-31

clear;
clc;

%% Section 1 Set project paths and fixed measures

% Define project-relative input and output locations.

this_file = mfilename('fullpath');
project_root = fileparts(fileparts(fileparts(fileparts(this_file))));
addpath(fullfile(project_root, 'src', 'utils'));

block_name = 'Block3_Clinical_Association';
result_dir = fullfile( ...
    project_root, 'results', block_name, 'TJU');
figure_dir = fullfile(result_dir, 'figures');

if ~isfolder(result_dir)
    mkdir(result_dir);
end
if ~isfolder(figure_dir)
    mkdir(figure_dir);
end

metadata_path = fullfile( ...
    project_root, 'Data', 'metadata', 'TJU_metadata.xlsx');

% Map each analysis measure to its exact metadata column suffix.
metadata_measure_columns = [ ...
    "Trail Making Test A"; ...
    "Trail Making Test B"; ...
    "CVLT Total Learning"; ...
    "CVLT Long Delay Free"; ...
    "RCFT Copy"; ...
    "Boston Naming Test"; ...
    "Phonemic Fluency (FAS)"; ...
    "Semantic Fluency (Animals)"; ...
    "WMS Logical Memory I"; ...
    "WMS Logical Memory II"; ...
    "WAIS Digit Span"; ...
    "WAIS Block Design"; ...
    "WAIS Vocabulary"];

% Define the ordered measure labels written to the paired-test table.
cognitive_measures = [ ...
    "Trail Making Test A"; ...
    "Trail Making Test B"; ...
    "CVLT Total Learning"; ...
    "CVLT Long Delay Free Recall"; ...
    "RCFT Copy"; ...
    "Boston Naming Test"; ...
    "Phonemic Fluency (FAS)"; ...
    "Semantic Fluency (Animals)"; ...
    "WMS Logical Memory I"; ...
    "WMS Logical Memory II"; ...
    "WAIS Digit Span"; ...
    "WAIS Block Design"; ...
    "WAIS Vocabulary"];

% Define stable tokens for subject-level standardized-score columns.
cognitive_tokens = [ ...
    "Trail_Making_Test_A"; ...
    "Trail_Making_Test_B"; ...
    "CVLT_Total_Learning"; ...
    "CVLT_Long_Delay_Free_Recall"; ...
    "RCFT_Copy"; ...
    "Boston_Naming_Test"; ...
    "Phonemic_Fluency_FAS"; ...
    "Semantic_Fluency_Animals"; ...
    "WMS_Logical_Memory_I"; ...
    "WMS_Logical_Memory_II"; ...
    "WAIS_Digit_Span"; ...
    "WAIS_Block_Design"; ...
    "WAIS_Vocabulary"];

% Define concise x-axis labels in the same order as the analysis measures.
display_labels = [ ...
    "TMT A"; ...
    "TMT B"; ...
    "CVLT Total Learning"; ...
    "CVLT Long Delay Free Recall"; ...
    "RCFT Copy"; ...
    "Boston Naming"; ...
    "Phonemic Fluency"; ...
    "Semantic Fluency"; ...
    "WMS Logical Memory I"; ...
    "WMS Logical Memory II"; ...
    "WAIS Digit Span"; ...
    "WAIS Block Design"; ...
    "WAIS Vocabulary"];

%% Section 2 Read the locked metadata

% Read the fixed TJU metadata and preserve its subject order in the output.

metadata = readtable( ...
    metadata_path, ...
    'Sheet', 'TJU_metadata', ...
    'VariableNamingRule', 'preserve');

subject_ids = strtrim(string(metadata.('Subject ID')));

% Preallocate one result value per cognitive measure.
n_measures = numel(cognitive_measures);
n_paired = zeros(n_measures, 1);
pre_mean_raw = nan(n_measures, 1);
pre_sd_raw = nan(n_measures, 1);
post_mean_raw = nan(n_measures, 1);
post_sd_raw = nan(n_measures, 1);
mean_delta_raw = nan(n_measures, 1);
delta_ci_lower = nan(n_measures, 1);
delta_ci_upper = nan(n_measures, 1);
paired_t = nan(n_measures, 1);
paired_df = nan(n_measures, 1);
cohen_dz = nan(n_measures, 1);
raw_p = nan(n_measures, 1);

z_score_table = table(subject_ids, 'VariableNames', {'Subject_ID'});

%% Section 3 Run paired tests on raw scores

% Use measure-specific complete pairs without imputation and define change as POST minus PRE.

for measure_index = 1:n_measures
    col_name = metadata_measure_columns(measure_index);
    token = cognitive_tokens(measure_index);
    pre_all = metadata.("Pre " + col_name);
    post_all = metadata.("Post " + col_name);
    paired_rows = ~isnan(pre_all) & ~isnan(post_all);
    pre_score = pre_all(paired_rows);
    post_score = post_all(paired_rows);
    delta_score = post_score - pre_score;

    n_paired(measure_index) = numel(delta_score);
    pre_mean_raw(measure_index) = mean(pre_score);
    pre_sd_raw(measure_index) = std(pre_score, 0);
    post_mean_raw(measure_index) = mean(post_score);
    post_sd_raw(measure_index) = std(post_score, 0);
    mean_delta_raw(measure_index) = mean(delta_score);

    % Estimate the paired mean change, its 95% CI, and Cohen's dz on the stored score scale.
    [~, raw_p(measure_index), confidence_interval, test_statistics] = ...
        ttest(post_score, pre_score);
    delta_ci_lower(measure_index) = confidence_interval(1);
    delta_ci_upper(measure_index) = confidence_interval(2);
    paired_t(measure_index) = test_statistics.tstat;
    paired_df(measure_index) = test_statistics.df;
    cohen_dz(measure_index) = mean(delta_score) / std(delta_score, 0);

    pre_z_all = nan(height(metadata), 1);
    post_z_all = nan(height(metadata), 1);
    % Standardize both time points to the complete-pair PRE mean and sample SD for plotting only.
    pre_z = (pre_score - mean(pre_score)) / std(pre_score, 0);
    post_z = (post_score - mean(pre_score)) / std(pre_score, 0);
    pre_z_all(paired_rows) = pre_z;
    post_z_all(paired_rows) = post_z;

    z_score_table.("Pre_" + token + "_Z") = pre_z_all;
    z_score_table.("Post_" + token + "_Z") = post_z_all;
end

%% Section 4 Apply FDR and write cognitive tables

% Adjust the 13 paired-test P values as one Benjamini-Hochberg FDR family.

fdr_p = mafdr(raw_p, 'BHFDR', true);
fdr_significant = fdr_p < 0.05;

% Write measure-level statistics using the script-defined output schema.
paired_test_table = table( ...
    cognitive_measures, n_paired, pre_mean_raw, pre_sd_raw, ...
    post_mean_raw, post_sd_raw, mean_delta_raw, delta_ci_lower, ...
    delta_ci_upper, paired_t, paired_df, cohen_dz, raw_p, fdr_p, ...
    'VariableNames', { ...
    'Cognitive_Measure', 'N_Paired', 'Pre_Mean_Raw', 'Pre_SD_Raw', ...
    'Post_Mean_Raw', 'Post_SD_Raw', 'Mean_Delta_Raw', ...
    'Delta_Raw_CI95_Lower', 'Delta_Raw_CI95_Upper', 'Paired_T', ...
    'Paired_DF', 'Cohen_dz', 'Raw_P', 'FDR_P'});

writetable(z_score_table, fullfile( ...
    result_dir, 'Pre_Post_Cognitive_Z_Scores.csv'));
writetable(paired_test_table, fullfile( ...
    result_dir, 'Pre_Post_Cognitive_Paired_Tests.csv'));

%% Section 5 Plot paired z scores

% Plot paired standardized scores with deterministic jitter and FDR-based annotations.

rng(20260803, 'twister');
cognitive_figure = figure( ...
    'Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1200, 750]);
axes_handle = axes(cognitive_figure);
hold(axes_handle, 'on');

pre_color = [76, 142, 218] / 255;
post_color = [231, 111, 106] / 255;
line_color = [0.82, 0.82, 0.82];
all_z_values = [];
pre_legend_handle = gobjects(1, 1);
post_legend_handle = gobjects(1, 1);

for measure_index = 1:n_measures
    token = cognitive_tokens(measure_index);
    pre_z_all = z_score_table.("Pre_" + token + "_Z");
    post_z_all = z_score_table.("Post_" + token + "_Z");
    paired_rows = ~isnan(pre_z_all) & ~isnan(post_z_all);
    pre_z = pre_z_all(paired_rows);
    post_z = post_z_all(paired_rows);
    jitter = (rand(numel(pre_z), 1) - 0.5) * 0.09;
    pre_x = measure_index - 0.14 + jitter;
    post_x = measure_index + 0.14 + jitter;

    for patient_index = 1:numel(pre_z)
        plot(axes_handle, ...
            [pre_x(patient_index), post_x(patient_index)], ...
            [pre_z(patient_index), post_z(patient_index)], '-', ...
            'Color', line_color, 'LineWidth', 0.7);
    end

    current_pre_handle = scatter( ...
        axes_handle, pre_x, pre_z, 18, pre_color, 'filled', ...
        'MarkerFaceAlpha', 0.75, 'MarkerEdgeColor', 'none');
    current_post_handle = scatter( ...
        axes_handle, post_x, post_z, 18, post_color, 'filled', ...
        'MarkerFaceAlpha', 0.75, 'MarkerEdgeColor', 'none');

    if measure_index == 1
        pre_legend_handle = current_pre_handle;
        post_legend_handle = current_post_handle;
    end

    all_z_values = [all_z_values; pre_z; post_z]; %#ok<AGROW>

    if fdr_significant(measure_index)
        local_maximum = max([pre_z; post_z]);
        bracket_bottom = local_maximum + 0.20;
        bracket_top = bracket_bottom + 0.18;
        plot(axes_handle, ...
            [measure_index - 0.14, measure_index - 0.14, ...
            measure_index + 0.14, measure_index + 0.14], ...
            [bracket_bottom, bracket_top, bracket_top, bracket_bottom], ...
            'k-', 'LineWidth', 1.0);

        if fdr_p(measure_index) < 0.001
            star_text = '***';
        elseif fdr_p(measure_index) < 0.01
            star_text = '**';
        else
            star_text = '*';
        end

        text(axes_handle, measure_index, bracket_top + 0.05, star_text, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'bottom', ...
            'FontSize', 15, 'FontWeight', 'bold');
    end
end

yline(axes_handle, 0, ':', 'Color', [0.45, 0.45, 0.45]);
xlim(axes_handle, [0.4, n_measures + 0.6]);
ylim(axes_handle, [min(all_z_values) - 0.35, max(all_z_values) + 0.85]);
xticks(axes_handle, 1:n_measures);
xticklabels(axes_handle, display_labels);
xtickangle(axes_handle, 48);
ylabel(axes_handle, 'z score');
title_obj = title(axes_handle, ...
    'Preoperative and Postoperative Cognitive Performance', ...
    'FontWeight', 'bold', 'FontSize', 14);
title_obj.Units = 'normalized';
title_obj.Position(2) = 1.04;
legend(axes_handle, [pre_legend_handle, post_legend_handle], ...
    {'Pre', 'Post'}, 'Location', 'northeast', 'Box', 'off', ...
    'Orientation', 'horizontal', 'FontSize', 13);
set(axes_handle, 'Box', 'off', 'FontName', 'Arial', 'FontSize', 13);

print(cognitive_figure, ...
    fullfile(figure_dir, 'Pre_Post_Cognitive_Z_Paired_Plot.png'), ...
    '-dpng', '-r300');
close(cognitive_figure);

fprintf('Step 1 completed for %d cognitive measures.\n', n_measures);
