% Step2_Run_TJU_Clinical_Associations: Univariable Clinical Associations with WMD Beta
%
% Purpose:
% Test associations between three patient-specific whole-brain WMD beta
% coefficients and seven surgical, clinical, and cognitive variables in the
% TJU cohort. Apply one Benjamini-Hochberg FDR correction across all 21 tests
% and generate the formal tables and figures.
%
% Author: Qirui Zhang
% Creation Date: 2026-08-31

%% Project paths and fixed analysis settings

% Define project-relative paths and the fixed analysis and display settings.

block_directory = string(fileparts(mfilename('fullpath')));
project_root = string(fileparts(fileparts(fileparts(block_directory))));
addpath(fullfile(project_root, 'src', 'utils'));

rsa_result_root = fullfile( ...
    project_root, 'results', 'Block2_WMD_RSA', 'TJU');
clinical_root = fullfile(project_root, 'results', ...
    'Block3_Clinical_Association', 'TJU');
figure_dir = fullfile(clinical_root, 'figures');

if ~isfolder(clinical_root)
    mkdir(clinical_root);
end
if ~isfolder(figure_dir)
    mkdir(figure_dir);
end

% Define the ordered beta analyses, source files, labels, and plot colors.
analysis_names = ["POST_FC"; "FUNC_REORG"; "MORPH_REORG"];
analysis_labels = [ ...
    "Postoperative FC"; ...
    "Functional reorganization"; ...
    "Morphometric reorganization"];
analysis_file_names = [ ...
    "POST_FC_RSA_Results.csv"; ...
    "FUNC_REORG_RSA_Results.csv"; ...
    "MORPH_REORG_RSA_Results.csv"];
analysis_colors = [ ...
    0.0000, 0.4470, 0.7410; ...
    0.8500, 0.3250, 0.0980; ...
    0.4660, 0.6740, 0.1880];

% Define the ordered clinical variables, analysis types, contrasts, and labels.
clinical_names = [ ...
    "Resection_Volume"; ...
    "TLE_Laterality"; ...
    "Seizure_Outcome"; ...
    "CVLT_Total_Learning_Delta"; ...
    "CVLT_Long_Delay_Free_Recall_Delta"; ...
    "Boston_Naming_Test_Delta"; ...
    "Semantic_Fluency_Animals_Delta"];
clinical_labels = [ ...
    "Resection volume"; ...
    "TLE laterality"; ...
    "Seizure outcome"; ...
    "CVLT Total Learning Delta"; ...
    "CVLT Long Delay Free Recall Delta"; ...
    "Boston Naming Test Delta"; ...
    "Semantic Fluency Animals Delta"];
clinical_types = [ ...
    "Continuous"; "Categorical"; "Categorical"; ...
    "Continuous"; "Continuous"; "Continuous"; "Continuous"];
contrast_directions = [ ...
    "Higher value"; ...
    "Right minus Left"; ...
    "Poor minus Good"; ...
    "More positive POST minus PRE change"; ...
    "More positive POST minus PRE change"; ...
    "More positive POST minus PRE change"; ...
    "More positive POST minus PRE change"];
x_axis_labels = [ ...
    "Resection volume (cm^3)"; ...
    "TLE laterality"; ...
    "Seizure outcome"; ...
    "CVLT Total Learning Delta (POST minus PRE)"; ...
    "CVLT Long Delay Free Recall Delta (POST minus PRE)"; ...
    "Boston Naming Test Delta (POST minus PRE)"; ...
    "Semantic Fluency Animals Delta (POST minus PRE)"];

rng(12); % Fix boxplot jitter across formal runs.

%% Read the locked TJU metadata and calculate cognitive change

% Read the fixed metadata and calculate all cognitive changes as POST minus PRE.

metadata = readtable(fullfile(project_root, 'Data', 'metadata', ...
    'TJU_metadata.xlsx'), 'Sheet', 'TJU_metadata', ...
    'VariableNamingRule', 'preserve', 'TextType', 'string');

subject_ids = strtrim(string(metadata.('Subject ID')));

laterality = strtrim(string(metadata.('TLE laterality')));
seizure_outcome = lower(strtrim(string( ...
    metadata.('Outcome 13 to 18 months category'))));

delta_cvlt_total = double(metadata.('Post CVLT Total Learning')) - ...
    double(metadata.('Pre CVLT Total Learning'));
delta_cvlt_delay = double(metadata.('Post CVLT Long Delay Free')) - ...
    double(metadata.('Pre CVLT Long Delay Free'));
delta_boston = double(metadata.('Post Boston Naming Test')) - ...
    double(metadata.('Pre Boston Naming Test'));
delta_semantic = double(metadata.('Post Semantic Fluency (Animals)')) - ...
    double(metadata.('Pre Semantic Fluency (Animals)'));

clinical_values = { ...
    double(metadata.('Resection volume')); ...
    laterality; ...
    seizure_outcome; ...
    delta_cvlt_total; ...
    delta_cvlt_delay; ...
    delta_boston; ...
    delta_semantic};

%% Read and align the three whole brain WMD beta vectors

% Align each fixed RSA beta vector to the metadata Subject ID order.

beta_matrix = nan(52, 3);
for analysis_index = 1:3
    rsa_table = readtable(fullfile(rsa_result_root, ...
        analysis_file_names(analysis_index)), ...
        'VariableNamingRule', 'preserve', 'TextType', 'string');
    rsa_subjects = strtrim(string(rsa_table.Subject_ID));
    [~, rsa_order] = ismember(subject_ids, rsa_subjects);
    aligned_beta = double(rsa_table.Standardized_Beta_WMD(rsa_order));
    beta_matrix(:, analysis_index) = aligned_beta;
end

%% Create the formal output directory

% Create the approved result directory when it is not already present.

if ~isfolder(clinical_root)
    mkdir(clinical_root);
end

%% Initialize the fixed 21 row result table

% Preallocate one row for each combination of three beta coefficients and seven variables.

n_tests = 21;
dataset_column = repmat("TJU", n_tests, 1);
analysis_column = strings(n_tests, 1);
clinical_variable_column = strings(n_tests, 1);
variable_type_column = strings(n_tests, 1);
contrast_column = strings(n_tests, 1);
n_total_column = nan(n_tests, 1);
group_one_column = strings(n_tests, 1);
n_group_one_column = nan(n_tests, 1);
mean_group_one_column = nan(n_tests, 1);
sd_group_one_column = nan(n_tests, 1);
group_two_column = strings(n_tests, 1);
n_group_two_column = nan(n_tests, 1);
mean_group_two_column = nan(n_tests, 1);
sd_group_two_column = nan(n_tests, 1);
mean_difference_column = nan(n_tests, 1);
ci_lower_column = nan(n_tests, 1);
ci_upper_column = nan(n_tests, 1);
spearman_rho_column = nan(n_tests, 1);
welch_t_column = nan(n_tests, 1);
degrees_of_freedom_column = nan(n_tests, 1);
hedges_g_column = nan(n_tests, 1);
heatmap_effect_column = nan(n_tests, 1);
p_value_column = nan(n_tests, 1);

heatmap_effects = nan(7, 3);
result_index = 0;

%% Run the univariable analyses

% Use complete observations for two-sided Spearman correlations and fixed group contrasts.

for analysis_index = 1:3
    beta_values = beta_matrix(:, analysis_index);

    for clinical_index = 1:7
        result_index = result_index + 1;
        analysis_column(result_index) = analysis_names(analysis_index);
        clinical_variable_column(result_index) = ...
            clinical_names(clinical_index);
        variable_type_column(result_index) = clinical_types(clinical_index);
        contrast_column(result_index) = ...
            contrast_directions(clinical_index);

        if clinical_types(clinical_index) == "Continuous"
            x_values = double(clinical_values{clinical_index});
            valid = isfinite(x_values) & isfinite(beta_values);
            n_complete = sum(valid);
            n_total_column(result_index) = n_complete;

            [rho_value, p_value] = corr(x_values(valid), ...
                beta_values(valid), 'Type', 'Spearman', ...
                'Rows', 'complete');
            spearman_rho_column(result_index) = rho_value;
            heatmap_effect_column(result_index) = rho_value;
            p_value_column(result_index) = p_value;
            heatmap_effects(clinical_index, analysis_index) = rho_value;
        else
            source_groups = string(clinical_values{clinical_index});
            if clinical_index == 2
                group_one_source = "Right";
                group_two_source = "Left";
                group_one_display = "Right";
                group_two_display = "Left";
            else
                group_one_source = "poor";
                group_two_source = "good";
                group_one_display = "Poor";
                group_two_display = "Good";
            end

            group_one_values = beta_values(source_groups == group_one_source);
            group_two_values = beta_values(source_groups == group_two_source);
            n_total_column(result_index) = ...
                numel(group_one_values) + numel(group_two_values);
            group_one_column(result_index) = group_one_display;
            n_group_one_column(result_index) = numel(group_one_values);
            group_two_column(result_index) = group_two_display;
            n_group_two_column(result_index) = numel(group_two_values);

            welch_result = calculate_welch_two_sample_statistics( ...
                group_one_values, group_two_values);
            mean_group_one_column(result_index) = ...
                welch_result.Mean_Group_One;
            sd_group_one_column(result_index) = welch_result.SD_Group_One;
            mean_group_two_column(result_index) = ...
                welch_result.Mean_Group_Two;
            sd_group_two_column(result_index) = welch_result.SD_Group_Two;
            mean_difference_column(result_index) = ...
                welch_result.Mean_Difference;
            ci_lower_column(result_index) = welch_result.CI95_Lower;
            ci_upper_column(result_index) = welch_result.CI95_Upper;
            welch_t_column(result_index) = welch_result.Welch_T;
            degrees_of_freedom_column(result_index) = ...
                welch_result.Welch_DF;
            hedges_g_column(result_index) = welch_result.Hedges_g;
            % Convert the Welch statistic to a bounded signed r for the heatmap.
            signed_effect = welch_result.Welch_T / sqrt( ...
                welch_result.Welch_T ^ 2 + welch_result.Welch_DF);
            heatmap_effect_column(result_index) = signed_effect;
            p_value_column(result_index) = welch_result.Raw_P;
            heatmap_effects(clinical_index, analysis_index) = signed_effect;
        end
    end
end

%% Apply BH FDR across all 21 clinical association tests

% Adjust all 21 two-sided P values as one Benjamini-Hochberg FDR family.

fdr_p_column = mafdr(p_value_column, 'BHFDR', true);
heatmap_fdr_p_values = reshape(fdr_p_column, 7, 3);

%% Create individual figures using FDR corrected results

% Generate all 21 approved figures with FDR-adjusted P values.

result_index = 0;
for analysis_index = 1:3
    beta_values = beta_matrix(:, analysis_index);

    for clinical_index = 1:7
        result_index = result_index + 1;
        plot_title = analysis_labels(analysis_index) + ...
            " WMD beta and " + clinical_labels(clinical_index);
        fdr_p_value = fdr_p_column(result_index);

        if clinical_types(clinical_index) == "Continuous"
            x_values = double(clinical_values{clinical_index});
            valid = isfinite(x_values) & isfinite(beta_values);
            figure_path = fullfile(figure_dir, ...
                analysis_names(analysis_index) + "_" + ...
                clinical_names(clinical_index) + "_Scatter.png");
            plot_wmd_clinical_scatter(x_values(valid), ...
                beta_values(valid), x_axis_labels(clinical_index), ...
                plot_title, analysis_colors(analysis_index, :), ...
                spearman_rho_column(result_index), fdr_p_value, figure_path);
        else
            source_groups = string(clinical_values{clinical_index});
            if clinical_index == 2
                display_groups = source_groups;
                display_order = ["Left"; "Right"];
            else
                display_groups = strings(size(source_groups));
                display_groups(source_groups == "good") = "Good";
                display_groups(source_groups == "poor") = "Poor";
                display_order = ["Good"; "Poor"];
            end

            figure_path = fullfile(figure_dir, ...
                analysis_names(analysis_index) + "_" + ...
                clinical_names(clinical_index) + "_Boxplot.png");
            plot_wmd_clinical_boxplot(beta_values, display_groups, ...
                display_order, plot_title, ...
                analysis_colors(analysis_index, :), ...
                hedges_g_column(result_index), fdr_p_value, figure_path);
        end
    end
end

%% Write the formal result table

% Write the 21 measure-level association results in analysis-major order.

result_table = table(dataset_column, analysis_column, ...
    clinical_variable_column, variable_type_column, contrast_column, ...
    n_total_column, group_one_column, n_group_one_column, ...
    mean_group_one_column, sd_group_one_column, group_two_column, ...
    n_group_two_column, mean_group_two_column, sd_group_two_column, ...
    mean_difference_column, ci_lower_column, ci_upper_column, ...
    spearman_rho_column, welch_t_column, degrees_of_freedom_column, ...
    hedges_g_column, heatmap_effect_column, p_value_column, ...
    fdr_p_column, ...
    'VariableNames', {'Dataset', 'Analysis', 'Clinical_Variable', ...
    'Variable_Type', 'Contrast_or_Direction', 'N_Total', 'Group_1', ...
    'N_Group_1', 'Mean_Group_1', 'SD_Group_1', 'Group_2', ...
    'N_Group_2', 'Mean_Group_2', 'SD_Group_2', 'Mean_Difference', ...
    'CI95_Lower', 'CI95_Upper', 'Spearman_Rho', 'Welch_T', ...
    'Degrees_of_Freedom', 'Hedges_G', 'Heatmap_Signed_Effect', ...
    'P_TwoSided', 'FDR_P_Across_21'});
writetable(result_table, fullfile(clinical_root, ...
    'Clinical_Univariable_Associations.csv'));

%% Write the patient-level WMD beta and clinical variables table

% Write the aligned beta coefficients and clinical variables for subject-level auditing.

display_seizure_outcome = repmat("Good", height(metadata), 1);
display_seizure_outcome(seizure_outcome == "poor") = "Poor";

patient_data_table = table( ...
    repmat("TJU", height(metadata), 1), ...
    subject_ids, ...
    beta_matrix(:, 1), ...
    beta_matrix(:, 2), ...
    beta_matrix(:, 3), ...
    double(metadata.('Resection volume')), ...
    laterality, ...
    display_seizure_outcome, ...
    delta_cvlt_total, ...
    delta_cvlt_delay, ...
    delta_boston, ...
    delta_semantic, ...
    'VariableNames', { ...
    'Dataset', 'Subject_ID', ...
    'POST_FC_Beta_WMD', 'FUNC_REORG_Beta_WMD', 'MORPH_REORG_Beta_WMD', ...
    'Resection_Volume', 'TLE_Laterality', 'Seizure_Outcome', ...
    'CVLT_Total_Learning_Delta', 'CVLT_Long_Delay_Free_Recall_Delta', ...
    'Boston_Naming_Test_Delta', 'Semantic_Fluency_Animals_Delta'});

writetable(patient_data_table, fullfile(clinical_root, ...
    'Patient_Clinical_and_WMD_Beta_Data.csv'));

%% Create the 7 by 3 summary heatmap

% Display Spearman rho or Welch-derived signed r with FDR-adjusted P values.

plot_wmd_clinical_heatmap(heatmap_effects, heatmap_fdr_p_values, ...
    clinical_labels, analysis_labels, fullfile(figure_dir, ...
    'Clinical_Association_Heatmap.png'));

fprintf('Step 2 completed for %d clinical association tests.\n', n_tests);
