function write_surgical_cavity_frequency_outputs( ...
    project_root, dataset, atlas_file, surgery_overlap_table, ...
    expected_patient_count)
% Purpose:
% Write center-level voxelwise cavity frequency and regional surgical
% involvement summaries from Original-orientation patient masks.
%
% Author: Qirui Zhang
% Created: 31 August 2026
%
%WRITE_SURGICAL_CAVITY_FREQUENCY_OUTPUTS Write center level cavity summaries.

% Voxelwise frequency is calculated on the original 1 mm atlas grid. ROI
% involvement is the percentage of patients whose overlap meets the fixed
% surgery affected threshold recorded in Surgery_ROI_Overlap.csv.
%
% project_root is the project root used to resolve relative mask and output
% paths. dataset identifies TJU or JLH. atlas_file supplies the original 1 mm
% reference header. surgery_overlap_table contains one Original mode row per
% patient and ROI. expected_patient_count is the center specific denominator.
%
% Prepared cavity masks are read directly and thresholded at values greater
% than or equal to 0.5. This function does not validate mask grid, affine, or
% binary value conformity. Voxelwise and ROI involvement outputs are reported
% as patient percentages.
%
% This function produces descriptive summaries and performs no hypothesis
% test or multiple testing correction.

arguments
    project_root (1, 1) string
    dataset (1, 1) string
    atlas_file (1, 1) string
    surgery_overlap_table table
    expected_patient_count (1, 1) double {mustBePositive, mustBeInteger}
end

required_variables = [ ...
    "Dataset", "Analysis_Mode", "Subject_ID", "ROI_ID", "ROI_Name", ...
    "Surgery_Mask_1mm", "Surgery_Affected"];
missing_variables = setdiff( ...
    required_variables, string(surgery_overlap_table.Properties.VariableNames));
if ~isempty(missing_variables)
    error( ...
        'Block1:CavityFrequencyMissingVariables', ...
        'Surgery overlap table is missing: %s.', ...
        strjoin(missing_variables, ', '));
end

if any(string(surgery_overlap_table.Dataset) ~= dataset) || ...
        any(string(surgery_overlap_table.Analysis_Mode) ~= "Original")
    error( ...
        'Block1:CavityFrequencyInputMismatch', ...
        'Cavity frequency outputs require one center in Original mode.');
end

% Identify the ordered patient set represented in the overlap table.
patient_ids = unique(string(surgery_overlap_table.Subject_ID), 'stable');
if numel(patient_ids) ~= expected_patient_count
    error( ...
        'Block1:CavityFrequencyPatientCountMismatch', ...
        'Expected %d patients for %s, found %d.', ...
        expected_patient_count, dataset, numel(patient_ids));
end

% Initialize the three dimensional voxelwise patient coverage count image.
atlas_info = niftiinfo(atlas_file);
cavity_coverage_count = zeros( ...
    double(atlas_info.ImageSize(1:3)), 'uint32');

% Accumulate prepared binary cavity masks across patients. No grid, affine,
% or binary value validation is performed in the formal calculation.
for patient_index = 1:numel(patient_ids)
    patient_rows = string(surgery_overlap_table.Subject_ID) == ...
        patient_ids(patient_index);
    mask_paths = unique(string( ...
        surgery_overlap_table.Surgery_Mask_1mm(patient_rows)));
    if numel(mask_paths) ~= 1
        error( ...
            'Block1:CavityFrequencyMaskCountMismatch', ...
            'Expected one 1 mm mask for %s, found %d.', ...
            patient_ids(patient_index), numel(mask_paths));
    end

    raw_cavity_mask = squeeze(niftiread( ...
        fullfile(project_root, mask_paths)));
    cavity_mask = raw_cavity_mask >= 0.5;
    cavity_coverage_count = cavity_coverage_count + uint32(cavity_mask);
end

cavity_frequency_percent = single(100) .* ...
    single(cavity_coverage_count) ./ single(expected_patient_count); % Patient coverage (%).
frequency_info = atlas_info;
frequency_info.Datatype = 'single';
frequency_info.BitsPerPixel = 32;

dataset_root = fullfile( ...
    project_root, 'results', 'Block1_TLE_surgery_reorganization', ...
    dataset, 'Original');
group_level_dir = dataset_root;
figure_dir = fullfile(dataset_root, 'figures');
if ~isfolder(group_level_dir)
    mkdir(group_level_dir);
end
if ~isfolder(figure_dir)
    mkdir(figure_dir);
end

% Write the voxelwise cavity frequency image in percent.
niftiwrite( ...
    cavity_frequency_percent, ...
    fullfile(figure_dir, ...
        'Voxelwise_Surgical_Cavity_Frequency_Percent.nii'), ...
    frequency_info, 'Compressed', true);

% Calculate the percentage of patients for whom each ROI meets the fixed
% 5 percent surgery affected threshold.
roi_reference = unique( ...
    surgery_overlap_table(:, {'ROI_ID', 'ROI_Name'}), ...
    'rows', 'stable');
n_rois = height(roi_reference);
n_patients_affected = zeros(n_rois, 1);

for roi_index = 1:n_rois
    roi_rows = surgery_overlap_table.ROI_ID == ...
        roi_reference.ROI_ID(roi_index);
    roi_patient_ids = string(surgery_overlap_table.Subject_ID(roi_rows));
    if numel(unique(roi_patient_ids)) ~= expected_patient_count
        error( ...
            'Block1:CavityFrequencyIncompleteROI', ...
            'ROI %d does not contain one row per patient.', ...
            roi_reference.ROI_ID(roi_index));
    end
    n_patients_affected(roi_index) = sum(logical( ...
        surgery_overlap_table.Surgery_Affected(roi_rows)));
end

involvement_percent = 100 .* n_patients_affected ./ ...
    expected_patient_count;
roi_involvement_table = table( ...
    repmat(dataset, n_rois, 1), ...
    repmat("Original", n_rois, 1), ...
    roi_reference.ROI_ID, string(roi_reference.ROI_Name), ...
    repmat(expected_patient_count, n_rois, 1), ...
    n_patients_affected, involvement_percent, ...
    'VariableNames', { ...
    'Dataset', 'Analysis_Mode', 'ROI_ID', 'ROI_Name', ...
    'N_Patients_Total', 'N_Patients_Surgery_Affected', ...
    'Patient_Involvement_Percent'});
writetable( ...
    roi_involvement_table, ...
    fullfile(group_level_dir, ...
        'Surgical_Cavity_ROI_Patient_Involvement.csv'));

% Render the cortical ROI involvement component with a fixed 0 to 60 percent
% color range.
mapping_file = fullfile( ...
    project_root, 'Data', 'atlas', ...
    'cocoyeo143_to_ENIGMA_schaefer100_mapping.csv');
mapping_table = readtable( ...
    mapping_file, 'VariableNamingRule', 'preserve');
[mapping_found, cortical_row_indices] = ismember( ...
    mapping_table.Project_ROI_ID, roi_reference.ROI_ID);
if any(~mapping_found)
    error( ...
        'Block1:CavityFrequencyMissingCorticalMapping', ...
        'At least one ENIGMA cortical parcel is missing from the ROI table.');
end
cortical_values = involvement_percent(cortical_row_indices);
cortical_surface_values = parcel_to_surface( ...
    cortical_values, 'schaefer_100_conte69', 0);

cortical_figure = figure('Visible', 'off', 'Color', 'white');
[~, cortical_colorbar] = plot_cortical( ...
    cortical_surface_values, ...
    'surface_name', 'conte69', ...
    'color_range', [0, 60], ...
    'cmap', 'Reds');
delete(cortical_colorbar);
print( ...
    cortical_figure, ...
    fullfile(figure_dir, ...
        'Surgical_Cavity_ROI_Patient_Involvement_Cortical.tiff'), ...
    '-dtiff', '-r300');
close(cortical_figure);

% Render the nonventricular subcortical involvement component with the same
% fixed 0 to 60 percent color range.
subcortical_enigma_roi_ids = ...
    [7; 6; 2; 5; 4; 3; 1; 15; 14; 10; 13; 12; 11; 9];
[subcortical_found, subcortical_row_indices] = ismember( ...
    subcortical_enigma_roi_ids, roi_reference.ROI_ID);
if any(~subcortical_found)
    error( ...
        'Block1:CavityFrequencyMissingSubcorticalMapping', ...
        'At least one ENIGMA subcortical ROI is missing from the ROI table.');
end
subcortical_values = involvement_percent(subcortical_row_indices);

subcortical_figure = figure('Visible', 'off', 'Color', 'white');
[~, subcortical_colorbar] = plot_subcortical( ...
    subcortical_values, ...
    'ventricles', 'False', ...
    'color_range', [0, 60], ...
    'cmap', 'Reds');
delete(subcortical_colorbar);
print( ...
    subcortical_figure, ...
    fullfile(figure_dir, ...
        'Surgical_Cavity_ROI_Patient_Involvement_Subcortical.tiff'), ...
    '-dtiff', '-r300');
close(subcortical_figure);
end
